%% generate_full_metasurface_lsf_905nm.m
% 将相位匹配矩阵转换为 Lumerical FDTD 的完整器件建模脚本。
% 运行本 MATLAB 文件后，得到 build_full_905nm_metasurface.lsf。
% 该 LSF 仅创建 SiO2 基底与 1200 个超胞内的 TiO2 双柱；
% 不创建或修改 FDTD solver、光源、监视器。

clear; clc;

this_dir = fileparts(mfilename('fullpath'));
matched_file = fullfile(this_dir, '905nm_phase_matched_structure_map.mat');
target_file = fullfile(fileparts(this_dir), '905nm_目标相位', ...
    'target_phases_905nm.mat');
lsf_file = fullfile(this_dir, 'build_full_905nm_metasurface.lsf');

assert(isfile(matched_file), '找不到匹配矩阵：%s', matched_file);
assert(isfile(target_file), '找不到目标相位文件：%s', target_file);

S = load(matched_file, 'matched');
T = load(target_file, 'X', 'Y', 'params');
M = S.matched;

required_maps = {'Lx1_map_m','Ly1_map_m','gap_map_m','Lx2_map_m','Ly2_map_m','x2_map_m'};
for k = 1:numel(required_maps)
    assert(isfield(M, required_maps{k}), '匹配矩阵缺少 %s。', required_maps{k});
end

[Ny, Nx] = size(M.Lx1_map_m);
assert(isequal(size(T.X), [Ny, Nx]) && isequal(size(T.Y), [Ny, Nx]), ...
    '匹配矩阵与目标相位网格尺寸不一致。');

Sx = T.params.Sx_m;
Sy = T.params.Sy_m;
height = 630e-9;
x1_local = -250e-9;
TiO2_material = 'TiO2 (Titanium Dioxide) - Devore';
SiO2_material = 'SiO2 (Glass) - Palik';
substrate_thickness = 1000e-9;

% 结构位置由目标相位网格给出；每个网格点即一个 supercell 中心。
x_center = T.X;
y_center = T.Y;
assert(abs(mean(diff(x_center(1,:))) - Sx) < 1e-15, 'x 向网格间距不是 Sx。');
assert(abs(mean(diff(y_center(:,1))) - Sy) < 1e-15, 'y 向网格间距不是 Sy。');

fid = fopen(lsf_file, 'w');
assert(fid > 0, '无法创建 LSF 文件：%s', lsf_file);
cleanup = onCleanup(@() fclose(fid));

fprintf(fid, '# Full 905 nm metasurface geometry generated by MATLAB\n');
fprintf(fid, '# %d x %d supercells; 2 TiO2 pillars per supercell.\n\n', Nx, Ny);
fprintf(fid, 'if (getnamednumber("full_metasurface")>0) {\n');
fprintf(fid, '    select("full_metasurface"); delete;\n');
fprintf(fid, '}\n\n');
fprintf(fid, 'addstructuregroup;\n');
fprintf(fid, 'set("name","full_metasurface");\n\n');

% 基底与柱体放进同一结构组；z=0 为基底顶面和柱底面。
fprintf(fid, 'addrect;\n');
fprintf(fid, 'set("name","SiO2_substrate");\n');
fprintf(fid, 'set("x",0); set("y",0);\n');
fprintf(fid, 'set("x span",%.16g); set("y span",%.16g);\n', Nx*Sx, Ny*Sy);
fprintf(fid, 'set("z min",%.16g); set("z max",0);\n', -substrate_thickness);
fprintf(fid, 'set("material","%s");\n', SiO2_material);
fprintf(fid, 'addtogroup("full_metasurface");\n\n');

for iy = 1:Ny
    for ix = 1:Nx
        xc = x_center(iy,ix);
        yc = y_center(iy,ix);
        x1 = xc + x1_local;
        x2 = xc + M.x2_map_m(iy,ix);

        write_pillar(fid, sprintf('pillar_1_%02d_%02d', ix, iy), ...
            x1, yc, M.Lx1_map_m(iy,ix), M.Ly1_map_m(iy,ix), height, TiO2_material);
        write_pillar(fid, sprintf('pillar_2_%02d_%02d', ix, iy), ...
            x2, yc, M.Lx2_map_m(iy,ix), M.Ly2_map_m(iy,ix), height, TiO2_material);
    end
end

fprintf(fid, '?"Full metasurface geometry created: %d supercells, %d pillars.";\n', ...
    Nx*Ny, 2*Nx*Ny);

fprintf('LSF 已生成：%s\n', lsf_file);

function write_pillar(fid, name, x, y, xspan, yspan, height, material_name)
fprintf(fid, 'addrect;\n');
fprintf(fid, 'set("name","%s");\n', name);
fprintf(fid, 'set("x",%.16g); set("y",%.16g);\n', x, y);
fprintf(fid, 'set("x span",%.16g); set("y span",%.16g);\n', xspan, yspan);
fprintf(fid, 'set("z min",0); set("z max",%.16g);\n', height);
fprintf(fid, 'set("material","%s");\n', material_name);
fprintf(fid, 'addtogroup("full_metasurface");\n\n');
end
